export * from "./AuthPage/";
export * from "./HomePage/";
export * from "./SettingsPage";
export * from "./ChangeInfoPage";
export * from "./ChangePasswordPage";
export * from "./NotFoundPage";
export * from "./ProfilePage";
export * from "./FriendsPage";
export * from "./LentaPage";
